name: Generate PDF

on:
  workflow_dispatch:

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
      - name: Regeneate page list
        run: yarn run en-pdf-list
      - name: Update page list
        run: |
          grep -v -F -f "pdf/docs.timeplus.com.excludes.txt" "pdf/docs.timeplus.com.txt" > a
          mv a "pdf/docs.timeplus.com.txt"
      - name: Regeneate PDF
        run: yarn run en-pdf-gen
      - name: Share PDF
        uses: actions/upload-artifact@v4
        with:
          path: pdf/docs.timeplus.com.pdf
