name: Spellchecker Timeplus

on:
  workflow_dispatch:  
env:
  PRINCE_VER: 15.3

jobs:
  spellchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  

      - name: Setup Node.js environment
        uses: actions/setup-node@v4  
        with:
          node-version: 18.0 

      - name: Install Yarn Dependencies
        run: yarn install  

      - name: Install Spellchecker CLI
        run: yarn global add spellchecker-cli # Install spellchecker-cli globally
        
      - name: Install Spellchecker Dev
        run: yarn add spellchecker-cli --dev
        
     
        
      - name: Run Spellchecker
        run: yarn run spellchecker 'docs/**/*.md' --config ./spellchecker/config.yml

      - name: Run spellchecker
        run: yarn run spellcheck --verbose
