name: Generate Spelling Error Report

on:
  workflow_dispatch:  

env:
  PRINCE_VER: 15.3

jobs:
  spellchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18.0 

      - name: Install Yarn Dependencies
        run: yarn install  

      - name: Install Spellchecker CLI
        run: yarn global add spellchecker-cli # Install spellchecker-cli globally

      - name: Run spellchecker
        run: yarn run spellcheck || true   # Runs the spellcheck command

      - name: Log spellcheck output
        run: |
          echo "Displaying spellcheck logs for debugging:"
          yarn run spellcheck || true

      - name: List all files
        run: |
          echo "Listing all files in the current directory and subdirectories:"
          ls -R

      - name: Check report.junit.xml
        run: |
          if [ -f "spellchecker/report.junit.xml" ]; then
            echo "Found spellchecker/report.junit.xml";
          else
            echo "spellchecker/report.junit.xml is missing!";
          fi

      - name: Check report.html
        run: |
          if [ -f "spellchecker/report.html" ]; then
            echo "Found spellchecker/report.html";
          else
            echo "spellchecker/report.html is missing!";
          fi

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Spellchecker Report
          path: spellchecker/report.html  # Upload the HTML report
